@echo off
echo Starting AI Fire Detection System...

echo Starting Backend (Checking dependencies & Running)...
echo This might take a while if downloading models/libraries...
start cmd /k "cd backend && venv\Scripts\python -m pip install -r requirements.txt && echo Starting Server... && venv\Scripts\python -m uvicorn main:app --reload --port 8000"

echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"

echo System initiating...
echo Backend: http://localhost:8000
echo Frontend: http://localhost:3000
